---
- name: Ensure group {{ unibody_nginx_group }} exists
  group:
    name: "{{ unibody_nginx_group }}"
    state: present
    system: yes

- name: Ensure user {{ unibody_nginx_user }} exists
  user:
    name: "{{ unibody_nginx_user }}"
    comment: "Analytics Unibody User"
    group: "{{ unibody_nginx_group }}"
    create_home: no
    system: yes
    shell: /sbin/nologin

- name: Create needed dirs - phase 1
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - /etc/nginx/ssl

- name: Create needed dirs - phase 2
  file:
    path: "{{ item }}"
    owner: "{{ unibody_nginx_user }}"
    group: "{{ unibody_nginx_group }}"
    mode: 0700
    state: directory
  with_items:
    - /var/lib/nginx
    - /var/lib/nginx/tmp
    - /var/lib/nginx/tmp/client_body

- name: Copy logrotate
  copy:
    src: etc/logrotate.d/nginx
    dest: /etc/logrotate.d/nginx
    group: root
    owner: root
    mode: 0644

- name: Copy SystemD file
  copy:
    src: usr/lib/systemd/system/nginx.service
    dest: /usr/lib/systemd/system/nginx.service
    group: root
    owner: root
    mode: 0644

- name: Make sure nginx starts at boot
  systemd:
    name: nginx
    enabled: yes
    masked: no
    daemon_reload: yes
