---

- name: install the 'development' environment group
  yum:
    name: "@development"
    state: present

- name: Install EPEL
  yum:
    name: "{{ unibody_epel_repo_rpm }}"
    state: present

- name: install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ unibody_required_packages }}"
